import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    mainSideBar: [
        {
            type: "doc",
            id: "index",
            className: "style_z",
        },
        {
            type: "category",
            label: "Plugins",
            collapsed: false,
            collapsible: false,
            items: [
                {
                    type: "link",
                    href: "https://wiki.lifestealz.com/",
                    label: "Lifestealz",
                    className: "style_lsz",
                },
                {
                    type: "link",
                    href: "/serverlinksz",
                    label: "ServerLinksZ",
                    className: "style_slz",
                },
            ],
        },
        {
            type: "link",
            href: "https://github.com/ZetaPlugins",
            label: "GitHub",
        },
        {
            type: "link",
            href: "https://strassburger.org/discord",
            label: "Discord",
        },
    ],

    serverlinksz: [
        {
            type: "doc",
            id: "serverlinksz/index",
        },
        {
            type: "doc",
            id: "serverlinksz/installation",
        },
    ],
};

export default sidebars;
