import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    mainSideBar: [
        {
            type: "doc",
            id: "index",
        },
        {
            type: "doc",
            id: "test",
        },
        {
            type: "category",
            label: "Plugins",
            items: [
                {
                    type: "link",
                    href: "/lifestealz",
                    label: "Lifestealz",
                },
                {
                    type: "link",
                    href: "/serverlinksz",
                    label: "ServerLinksZ",
                },
            ],
        },
    ],

    lifestealz: [
        {
            type: "doc",
            id: "lifestealz/index",
        },
        {
            type: "doc",
            id: "lifestealz/installation",
        },
        {
            type: "category",
            label: "⚡ Commands",
            items: [
                {
                    type: "doc",
                    id: "lifestealz/commands/lifestealz",
                },
                {
                    type: "doc",
                    id: "lifestealz/commands/withdrawheart",
                },
                {
                    type: "doc",
                    id: "lifestealz/commands/hearts",
                },
                {
                    type: "doc",
                    id: "lifestealz/commands/eliminate",
                },
                {
                    type: "doc",
                    id: "lifestealz/commands/revive",
                },
            ],
        },
        {
            type: "category",
            label: "🛠️ Configuration",
            items: [
                {
                    type: "doc",
                    id: "lifestealz/config/configmain",
                },
                {
                    type: "doc",
                    id: "lifestealz/config/messages",
                },
                {
                    type: "doc",
                    id: "lifestealz/config/customitems",
                },
                {
                    type: "doc",
                    id: "lifestealz/config/whitelist",
                },
                {
                    type: "doc",
                    id: "lifestealz/config/datamigration",
                },
            ],
        },
    ],

    serverlinksz: [
        {
            type: "doc",
            id: "serverlinksz/index",
        },
        {
            type: "doc",
            id: "serverlinksz/installation",
        },
    ],
};

export default sidebars;
